### PR TITLE
Fix leg bat stats

### PR DESCRIPTION
**Pull request by TymanWasTaken**

### CODE REVIEW

**Review by SemicolumnDev — CHANGES_REQUESTED** [review]
"Base Stats" are a level 0 pet, though I think otherNums needs to be changed anyway.
image

**Comment by TymanWasTaken** [comment]
Oops, thanks for pointing that out

**Comment by IRONM00N** [comment]
Do you still plan on doing this?

**Comment by TymanWasTaken** [comment]
Yes, I'll just make a new pr

**Pull request closed without merging**
