### PR TITLE
This can be done on a ASPECT_OF_THE_VOID

### PR DESCRIPTION
**Pull request by UP929312**
AOTV is an EPIC item which can be recombobulated into a legendary, hence the new bracket.

### CODE REVIEW

**Review by jani270 — CHANGES_REQUESTED** [review]
The JSON is invalid. Please use a JSON Validator like https://jsonformatter.curiousconcept.com/# to verify your changes.

**Comment by UP929312** [comment]
> The JSON is invalid. Please use a JSON Validator like https://jsonformatter.curiousconcept.com/# to verify your changes.

Okay, it passes, oops, missed a " and a } but should be good now

**Review by jani270 — APPROVED** [review]
Looks fine! 👍

**Comment by UP929312** [comment]
This got overwritten?
https://github.com/Moulberry/NotEnoughUpdates-REPO/blob/master/constants/reforgestones.json#L1962

**Comment by UP929312** [comment]
@jani270

**Comment by jani270** [comment]
> @jani270

Wdym you pr is not merged

**Pull request merged**
