### PR TITLE
Update to Fairy Armor (and maybe other armors)

### PR DESCRIPTION
**Pull request by L1ghtRay**

### CODE REVIEW

**Comment by L1ghtRay** [comment]
its kind of like a suggestion is i should do the same format change with other pieces of fairy armour and other armours

**Comment by Eejit43** [comment]
On the [wiki](https://hypixel-skyblock.fandom.com/wiki/Fairy_Armor), you can see the default tooltip. It shows `0 Fairy Souls` as default, rather than `000`.

**Comment by L1ghtRay** [comment]
> On the [wiki](https://hypixel-skyblock.fandom.com/wiki/Fairy_Armor), you can see the default tooltip. It shows `0 Fairy Souls` as default, rather than `000`. Not sure if you want to display it like that instead, however.

It doesn't show 000 it shows the randomising sga characters

**Comment by IRONM00N** [comment]
> > On the [wiki](https://hypixel-skyblock.fandom.com/wiki/Fairy_Armor), you can see the default tooltip. It shows `0 Fairy Souls` as default, rather than `000`. Not sure if you want to display it like that instead, however.
> 
> It doesn't show 000 it shows the randomising sga characters

This is how I would like stat dependent numbers to be shown

**Review by IRONM00N — APPROVED** [review]

**Pull request merged**
