### PR TITLE
Update SNOW_SHOVEL.json

### PR DESCRIPTION
**Pull request by apotato321**
fine jani ill fix it

### CODE REVIEW

**Comment by DeDiamondPro** [comment]
That’s the cost to place the snow and not the cost of the item, it should be there.

**Comment by jani270** [comment]
ty <3

**Comment by jani270** [comment]
wait 4real?

**Comment by DeDiamondPro** [comment]
> wait 4real?

Yes, check it at the dude on top of the mountain

**Comment by jani270** [comment]
Clown Moment from me

**Pull request closed without merging**
