### PR TITLE
Mobs & Names + Fixes

### PR DESCRIPTION
**Pull request by jani270**
Added Rainbownames
Changed all Mobs to Skulls
Deleted animals and some useless mobs
Fixed some Items

### CODE REVIEW

**Comment by IRONM00N** [comment]
Jani I changed my mind 😳, I am not sure if I want the mobs deleted.

**Comment by IRONM00N** [comment]
I will think about it and lyk what I think.

**Comment by jani270** [comment]
> Jani I changed my mind 😳, I am not sure if I want the mobs deleted.

Insert WeirdChamp here. Spider Slime and Zombie should be deleted, they are like 5 other spider mobs same for slime and zombie

**Comment by jani270** [comment]
@IRONM00N There, now merge pls

**Pull request merged**
