### PR TITLE
Added the New Pet Skins

### PR DESCRIPTION
**Pull request by MisterCheezeCake**
Added Neon Red, Blue, and Purple Ender Dragon Skins

### CODE REVIEW

**Comment by MisterCheezeCake** [comment]
uhh what did I do wrong?

**Comment by DeDiamondPro** [comment]
> uhh what did I do wrong?

I can't find it either, I also added them to my fork and then you finished first, if you say that I can create a pull request for mine I will.

**Comment by MisterCheezeCake** [comment]
> > uhh what did I do wrong?
> 
> I can't find it either, I also added them to my fork and then you finished first, if you say that I can create a pull request for mine I will.

sure you can do that

**Comment by DeDiamondPro** [comment]
> > > uhh what did I do wrong?
> > 
> > 
> > I can't find it either, I also added them to my fork and then you finished first, if you say that I can create a pull request for mine I will.
> 
> sure you can do that

ok thanks

**Comment by IRONM00N** [comment]
> uhh what did I do wrong?

Your nbt tags are scuffed, there is a backslash but no quote on the 4th line

**Pull request closed without merging**
