### PR TITLE
Newer New Alpha Items

### PR DESCRIPTION
**Pull request by Strebbypatty**
New weaponsmith items

### CODE REVIEW

**Comment by DeDiamondPro** [comment]
Change target to alpha branch

**Comment by Strebbypatty** [comment]
Ill fix this later today currently on a beach trip

**Comment by Strebbypatty** [comment]
Pro tip: Editing on a phone is not fun

**Comment by Strebbypatty** [comment]
Oh wait sorry ironmoon I just saw I forgot to delete the comma everytime at the end

**Comment by IRONM00N** [comment]
I can fix it

**Comment by Strebbypatty** [comment]
Ok I managed to change all items on my phone except for the new flint arrow, which is replacing the vanilla minecraft arrow btw, but Ill look into that tonight when Im on my pc

**Comment by Strebbypatty** [comment]
Quickly deleted the npc information of the flint arrow already like I did with the other items, Ill check the other stuff about the recipe and wiki link later tonight on my pc

**Comment by Strebbypatty** [comment]
Ok Im back on my pc and checked on the alpha network and I can now officially confirm vanilla arrows dont exist anymore, you can still craft them using the vanilla recipe though so Ill add that to the file again together with the wiki link that will hopefully get updated soon.

**Comment by Strebbypatty** [comment]
Ok everything should be good now I think so tell me when Im allowed to put it up for review

**Comment by Strebbypatty** [comment]
How do I reopen for main branch? :)

**Pull request closed without merging**
