### PR TITLE
Remove uuids from items

### PR DESCRIPTION
**Pull request by TymanWasTaken**
Still in progress

~~I did this mostly by hand lol~~

### CODE REVIEW

**Comment by IRONM00N** [comment]
Please don’t do this by hand

**Comment by TymanWasTaken** [comment]
> Please don’t do this by hand

Its only *partially* by hand

**Comment by IRONM00N** [comment]
@TymanWasTaken why is this a draft?

**Comment by TymanWasTaken** [comment]
Because I'm not done yet

**Comment by TymanWasTaken** [comment]
Merge it if you want ig tho it doesn't really matter I'll just make another pr

**Comment by TymanWasTaken** [comment]
should I squash all these commits so its not one giant line of commits @IRONM00N

**Comment by IRONM00N** [comment]
No, just leave it

**Comment by IRONM00N** [comment]
I hope this doesn’t break anything

**Comment by TymanWasTaken** [comment]
it shouldn't and its easy to revert

**Pull request merged**
