### PR TITLE
Added nullzee and me to special boys

### PR DESCRIPTION
**Pull request by TomEngMaster**

### CODE REVIEW

**Comment by SemicolumnDev** [comment]
Remove tomengmaster and then it will be good

**Comment by nopothegamer** [comment]
add me smh

**Comment by SemicolumnDev** [comment]
add me looser

**Comment by SemicolumnDev** [comment]
> add me smh
> 

more like nopothegay

**Comment by riohorealhk** [comment]
ikr add nopo

**Comment by SemicolumnDev** [comment]
> ikr add nopo

shutup clowbn

**Comment by riohorealhk** [comment]
heh ur gayer

**Comment by SemicolumnDev** [comment]
> heh ur gayer 
> 

more like riohogay gay looser

**Comment by MisterCheezeCake** [comment]
I am a cool human add me too
6a24734e-7d9f-4abf-bf9e-c56bf5428f1b

**Comment by IRONM00N** [comment]
Only Moulberry can add people as cool

**Pull request closed without merging**
