### PR TITLE
Add new workflow

### PR DESCRIPTION
**Pull request by DeDiamondPro**
This workflow only runs on new pull requests.
Advantages of this workflow:
- it is way faster since it only does files that have changed
- it says around where json has failed parsing
- it checks if the item has internal name, display name and item id
- it checks if the lore in the nbt tag is the same as the lore 
-  it checks if the lore includes a uuid or timestamp and then gives a warning
(Sorry for 106 commits but well you need to test stuff like this by commiting)

### CODE REVIEW

**Comment by DeDiamondPro** [comment]
I think it failed because it doesn't have permission to see something that fixes when merged idk I haven't had this problem while testing

**Comment by IRONM00N** [comment]
Ill look at this more in a bit over a week so don't feel as if I am ignoring you its just that I don't have time to check this many lines of code until then. I may also only use some of the stuff you did (give you commit credit ofc) since i have w few other things in mind

**Comment by IRONM00N** [comment]
also it's probably better to have this in a different repo so this doesn't need to be pulled every time someone downloads the item list.

**Comment by DeDiamondPro** [comment]
> also it's probably better to have this in a different repo so this doesn't need to be pulled every time someone downloads the item list.

Yeah okay, if you allow me to I think I can create a new repo inside the notenoughupdates organization, also I do not recommend reading deps/index.js because it’s a file with every file that would normally be inside node_modules (created using ncc)

**Comment by IRONM00N** [comment]
> > also it's probably better to have this in a different repo so this doesn't need to be pulled every time someone downloads the item list.
> 
> Yeah okay, if you allow me to I think I can create a new repo inside the notenoughupdates organization, also I do not recommend reading dist/index.js because it’s a file with every file that would normally be inside node_modules (created using ncc)

yea

**Comment by IRONM00N** [comment]
also this needs to be rewritten in typescript :)

**Comment by DeDiamondPro** [comment]
New pr soon:tm:

**Pull request closed without merging**
