### PR TITLE
Update misc.json

### PR DESCRIPTION
**Pull request by Artiik373**
raven reyes is special too

### CODE REVIEW

**Review by apotato321 — CHANGES_REQUESTED** [review]
Add me in there too !!

**Comment by Artiik373** [comment]
> Add me in there too !!

done!!

**Comment by nopothegamer** [comment]
i would like rgb name ty

**Review by apotato321 — APPROVED** [review]

**Review by TrashCan69420 — APPROVED** [review]

**Comment by Artiik373** [comment]
@nopothegamer added!

**Review by nopothegamer — APPROVED** [review]
yes

**Review by apotato321 — APPROVED** [review]

**Review by nopothegamer — APPROVED** [review]

**Review by nopothegamer — APPROVED** [review]

**Review by nopothegamer — APPROVED** [review]

**Review by nopothegamer — APPROVED** [review]

**Review by TymanWasTaken — APPROVED** [review]

**Review by TomEngMaster — APPROVED** [review]

**Review by apotato321 — APPROVED** [review]

**Review by apotato321 — DISMISSED** [review]

**Review by TymanWasTaken — DISMISSED** [review]

**Review by IRONM00N — APPROVED** [review]

**Comment by IRONM00N** [comment]
ask moul only he can decide

**Comment by apotato321** [comment]
sad

**Comment by Swedengamer100** [comment]
Can one join the special train?

**Pull request closed without merging**
