### PR TITLE
Fixed Griffin Upgrade Stones

### PR DESCRIPTION
**Pull request by jani270**
enchnated > enchanted 

:)

### CODE REVIEW

**Comment by IRONM00N** [comment]
I bet you I was the one that made the error

**Comment by MisterCheezeCake** [comment]
Oops I may have not changed the NBT data when I fixed those a while back

**Comment by jani270** [comment]
> Oops I may have not changed the NBT data when I fixed those a while back

the nbt data was not the problem

**Comment by MisterCheezeCake** [comment]
> > Oops I may have not changed the NBT data when I fixed those a while back
> 
> the nbt data was not the problem

yeah, although I just noticed that  I did that

**Pull request merged**
