### PR TITLE
Books (WIP)

### PR DESCRIPTION
**Pull request by jani270**
Do not merge this, please. 

Just looking for a maybe invalid JSON, also if you want to do something here you can see my progress

### CODE REVIEW

**Comment by IRONM00N** [comment]
*continues to merge it anyways*

**Comment by jani270** [comment]
> _continues to merge it anyways_

just no

**Comment by IRONM00N** [comment]
> > _continues to merge it anyways_
> 
> just no

:)

**Comment by jani270** [comment]
Im doing a new pr for this if its rdy

**Pull request closed without merging**
