### PR TITLE
Bestiary

### PR DESCRIPTION
**Pull request by ENORMOUZ**
Add bestiary commands to items

### CODE REVIEW

**Comment by ENORMOUZ** [comment]
Adding bestiary links now

**Comment by jani270** [comment]
???????????????????

**Review by jani270 — CHANGES_REQUESTED** [review]
Why do you add Bestiary to that, it dosent even make sense
The command just opens the menu which is stupid
Also some of them Mobs are not even in the Bestiary 
Also if you add it the Lore says: View Recipe! which also dosent even make sense.
Also the command just dosent work.

Please remove the bestiary things again

**Comment by ENORMOUZ** [comment]
Bruh...ok

**Pull request closed without merging**
