### PR TITLE
SB Changes, Mobs Part 2 and Easter Things

### PR DESCRIPTION
**Pull request by jani270**
Added Cosmetics 
Added Mobs
Changed Mobs to Bestiary
Changed SC's Info
Changed "everything" from the last SB Update
Added Dante Things

Big Pr poggers

### CODE REVIEW

**Comment by jani270** [comment]
bruh

**Comment by jani270** [comment]
Iron have fun :)

**Comment by IRONM00N** [comment]
Ahhhh, so much reading, it looks good but I am going to test in-game just to double check

**Comment by jani270** [comment]
> Ahhhh, so much reading, it looks good but I am going to test in-game just to double check

yea sure, tested it on 2 different pc's and it works fine

**Comment by IRONM00N** [comment]
> > Ahhhh, so much reading, it looks good but I am going to test in-game just to double check
> 
> yea sure, tested it on 2 different pc's and it works fine

I don't need moul yelling at me

**Comment by jani270** [comment]
> > > Ahhhh, so much reading, it looks good but I am going to test in-game just to double check
> > 
> > 
> > yea sure, tested it on 2 different pc's and it works fine
> 
> I don't need moul yelling at me

xd

**Pull request merged**
