### PR TITLE
Take 2: Added enchantments and fixed parenting

### PR DESCRIPTION
**Pull request by Swedengamer100**

### CODE REVIEW

**Comment by Swedengamer100** [comment]
Why does it keep failing with the check?

**Comment by jani270** [comment]
Because your parents.json is invalid

**Comment by jani270** [comment]
and http://prntscr.com/w6bpwo why is that offset

**Comment by Swedengamer100** [comment]
> and http://prntscr.com/w6bpwo why is that offset

That's weird, when I edited it it was in line

**Comment by jani270** [comment]
> > and http://prntscr.com/w6bpwo why is that offset
> 
> That's weird, when I edited it it was in line

btw that was just an example, it's everywhere

**Comment by jani270** [comment]
pog

**Pull request merged**
