### PR TITLE
New PR because I am stupid

### PR DESCRIPTION
**Pull request by TymanWasTaken**
(wedding rings for romero and juliette quest)

### CODE REVIEW

**Review by apotato321 — CHANGES_REQUESTED** [review]
Some changes, like deleting the UUID and obtained date for the items, as well as for classy ring of love there is not a wiki link. Also I would assume that you would want to parent everything

**Review by apotato321 — DISMISSED** [review]

**Comment by TymanWasTaken** [comment]
> Some changes, like deleting the UUID and obtained date for the items, as well as for classy ring of love there is not a wiki link. Also I would assume that you would want to parent everything

1. Yeah I fixed the wiki url
2. I can probably delete the extra data when I get the chance tomorrow
3. How do you parent things

**Review by apotato321 — APPROVED** [review]

**Review by SemicolumnDev — APPROVED** [review]

**Comment by IRONM00N** [comment]
don’t add yourself to cool dudes only moul can do that

**Review by IRONM00N — CHANGES_REQUESTED** [review]
smh

**Review by IRONM00N — APPROVED** [review]

**Pull request merged**
