### PR TITLE
Upcoming Gemstone Changes 

### PR DESCRIPTION
**Pull request by jani270**
Missing:
- Reforge Stats for the new rarity (some done)

### CODE REVIEW

**Comment by Eejit43** [comment]
Just so you know, Divine rarity color was changed to `§b` (it appears to be a bit buggy though) ([proof](https://media.discordapp.net/attachments/825496996990550027/886427455454322739/unknown.png)).

**Comment by jani270** [comment]
I hate Hypixel :)

**Comment by IRONM00N** [comment]
if you push a new commit the check will work properly

**Comment by jani270** [comment]
> if you push a new commit the check will work properly

thank you

**Comment by Eejit43** [comment]
I can create a PR, but the Jungle Pickaxe was updated too, if you want to fix that in this PR.

**Comment by jani270** [comment]
> I can create a PR, but the Jungle Pickaxe was updated too, if you want to fix that in this PR.

As you can see they changed a lot of other stuff but there is only 1 thing missing

**Review by IRONM00N — APPROVED** [review]

**Pull request merged**
