### PR TITLE
Romero Quest Items

### PR DESCRIPTION
**Pull request by apotato321**
Some were already in repo, so I did the rest.

### CODE REVIEW

**Comment by DeDiamondPro** [comment]
Respect

**Comment by jani270** [comment]
Respect

but no wiki links eww

**Comment by apotato321** [comment]
> Respect
> 
> but no wiki links eww

oops hold on

**Comment by TymanWasTaken** [comment]
oh when I did all the rings I didn't even think to add all the other items you get while doing the quest

also why make a new pr just edit this one?

**Comment by apotato321** [comment]
> oh when I did all the rings I didn't even think to add all the other items you get while doing the quest
> 
> also why make a new pr just edit this one?
I don't know how to really edit the pr because I'm dumb

**Comment by TymanWasTaken** [comment]
> > oh when I did all the rings I didn't even think to add all the other items you get while doing the quest
> > also why make a new pr just edit this one?
> 
> I don't know how to really edit the pr because I'm dumb

To add new commits just change on whatever branch shows here 
Screenshot_20210228-074512

**Pull request closed without merging**
