### PR TITLE
Fixed slayer exp on bosses 

### PR DESCRIPTION
**Pull request by MisterCheezeCake**
Fixed sven and taras saying they gave eman exp.

### CODE REVIEW

**Review by ENORMOUZ — APPROVED** [review]
Seems good!

**Comment by jani270** [comment]
> Seems good!

Like the 0 and the O?

**Review by jani270 — APPROVED** [review]
Seems fine, could you just please make new branches for your changes this commit history is a mess.

**Comment by MisterCheezeCake** [comment]
> Seems fine, could you just please make new branches for your changes this commit history is a mess.

Noted

**Review by IRONM00N — APPROVED** [review]

**Pull request merged**
