### PR TITLE
Even more Newest Newer New, jk its just the new Nether Artifact :) also jani asked me to do some stuff now so its alot of stuff actually

### PR DESCRIPTION
**Pull request by Strebbypatty**

### CODE REVIEW

**Comment by Strebbypatty** [comment]
dont merge yet

**Comment by Strebbypatty** [comment]
Im being professional

**Comment by Strebbypatty** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by IRONM00N** [comment]
bro just use the in-game item editor

**Comment by Strebbypatty** [comment]
> bro just use the in-game item editor

yes currently doing that because me very smart

**Comment by Strebbypatty** [comment]
LETS GO I DID IT

**Comment by Strebbypatty** [comment]
Casually deleted all wiki links

**Comment by Strebbypatty** [comment]
ok Im succesfully making it worse

**Comment by Strebbypatty** [comment]
ok I fixed all items that can have gemstones applied to them to gray out the slots that arent unlocked by base and also fixed some other stuff

**Comment by Strebbypatty** [comment]
Ironmoon prepare yourself

**Comment by Strebbypatty** [comment]
Have fun good sir

**Comment by Strebbypatty** [comment]
> ok I fixed all items that can have gemstones applied to them to gray out the slots that arent unlocked by base and also fixed some other stuff

also did this, added 2 new items (nether artifact and sabertooth tiger skin) and fixed divan and mithril golem lore

**Comment by Strebbypatty** [comment]
you can merge now if everything is alright

**Comment by Strebbypatty** [comment]
nvm not done yet forgot that there also are items without hp that still have the gap between red and green stats which isnt the case now anymore so still need to change all those

**Pull request merged**
