### PR TITLE
added fire badges

### PR DESCRIPTION
**Pull request by DeDiamondPro**

### CODE REVIEW

**Comment by DeDiamondPro** [comment]
420 nice

**Comment by jani270** [comment]
> 420 nice

cool

**Comment by IRONM00N** [comment]
Why do you do every file individually, this pains me.

**Comment by jani270** [comment]
> Why do you do every file individually, this pains me.

wdym

**Comment by IRONM00N** [comment]
There is no need to make a commit for each file, just use a couple commits

**Comment by jani270** [comment]
> There is no need to make a commit for each file, just use a couple commits

wdym its not each file

**Comment by IRONM00N** [comment]
> > There is no need to make a commit for each file, just use a couple commits
> 
> wdym its not each file

Okay but it is still a lot of commits

**Comment by jani270** [comment]
> > > There is no need to make a commit for each file, just use a couple commits
> > 
> > 
> > wdym its not each file
> 
> Okay but it is still a lot of commits

and where is the problem?

**Comment by DeDiamondPro** [comment]
> > > There is no need to make a commit for each file, just use a couple commits
> > 
> > 
> > wdym its not each file
> 
> Okay but it is still a lot of commits

that looks cooler :D

**Comment by IRONM00N** [comment]
> > > > There is no need to make a commit for each file, just use a couple commits
> > > 
> > > 
> > > wdym its not each file
> > 
> > 
> > Okay but it is still a lot of commits
> 
> and where is the problem?

I said it pains me, I never said there is a problem

**Comment by jani270** [comment]
> > > > > There is no need to make a commit for each file, just use a couple commits
> > > > 
> > > > 
> > > > wdym its not each file
> > > 
> > > 
> > > Okay but it is still a lot of commits
> > 
> > 
> > and where is the problem?
> 
> I said it pains me, I never said there is a problem

Okay it pains me that you not give me my rainbow name. Sadge

**Pull request merged**
