### PR TITLE
Add bestower(sr mod) to special name

### PR DESCRIPTION
**Pull request by Mr-PenguinMan**
Plz...

### CODE REVIEW

**Comment by TrashCan69420** [comment]
didnt ask

**Comment by Mr-PenguinMan** [comment]
> didnt ask

it... must happen

**Comment by TrashCan69420** [comment]
> 
> 
> > didnt ask
> 
> it... must happen

ill bet moul wont accept the pr

**Comment by IRONM00N** [comment]
Only moul can add people, stop making prs.

**Pull request closed without merging**
