### PR TITLE
New Alpha Items (but I'm MVP++ so I'm special)

### PR DESCRIPTION
**Pull request by Strebbypatty**

### CODE REVIEW

**Comment by nopothegamer** [comment]
oil barral and i think yoggie was alr in someone else's pr

**Comment by DeDiamondPro** [comment]
> oil barral and i think yoggie was alr in someone else's pr

I removed oil barrel because I fucked up somewhere and yoggie isn't I think

**Comment by nopothegamer** [comment]
> > oil barral and i think yoggie was alr in someone else's pr
> 
> I removed oil barrel because I fucked up somewhere and yoggie isn't I think

oh ok

**Comment by Strebbypatty** [comment]
I looked and it is NOT

**Comment by Strebbypatty** [comment]
I'm very good

**Comment by DeDiamondPro** [comment]
> I'm very good

lies

**Review by IRONM00N — APPROVED** [review]

**Pull request merged**
