### PR TITLE
Fix crafting recipes of some items

### PR DESCRIPTION
**Pull request by ENORMOUZ**
Fix ENCHANTED_LAPIS_LAZULI_BLOCK craft

### CODE REVIEW

**Comment by ENORMOUZ** [comment]
Also, is it when this change is accepted, then all my fixes to recipes in the future will be auto accepted?

**Comment by ENORMOUZ** [comment]
Updated the info link.

**Comment by ENORMOUZ** [comment]
Why does my pull request have "conflicts"? i just edit some item name to be correct

**Comment by ENORMOUZ** [comment]
Added a recipe to the flower of truth

**Comment by ENORMOUZ** [comment]
Fixed a lot of recipes

**Review by IRONM00N — APPROVED** [review]
looks good

**Pull request merged**
