### PR TITLE
Fix Mythos Mob drops

### PR DESCRIPTION
**Pull request by 8KCoffeeWizard**
Added Minos Relic, Shelmet, Remedies, and Plushie as possible drops from Inquisitors

### CODE REVIEW

**Review by DeDiamondPro — CHANGES_REQUESTED** [review]
Update the lore inside the nbttag

**Comment by 8KCoffeeWizard** [comment]
> 
> 
> Update the lore inside the nbttag

done, hopefully didnt mess it up

**Review by jani270 — CHANGES_REQUESTED** [review]
You still didnt update the NBT Tag from the Minos Champion

**Comment by 8KCoffeeWizard** [comment]
> 
> 
> You still didnt update the NBT Tag from the Minos Champion

:pensivewobble:
also hopefully didn't break stuff v2

**Review by IRONM00N — APPROVED** [review]

**Pull request merged**
