### PR TITLE
Guardian pet -> Enchanting pet, Experimentation table, other new items and recipes/wiki links

### PR DESCRIPTION
**Pull request by Swedengamer100**

### CODE REVIEW

**Review by MisterCheezeCake — DISMISSED** [review]
Looks all good to me.

**Comment by IRONM00N** [comment]
AAAAAAAAAAA, my notifications

**Comment by Swedengamer100** [comment]
> AAAAAAAAAAA, my notifications

Sorry, uploaded them to the wrong place

**Review by SemicolumnDev — CHANGES_REQUESTED** [review]
Line 10 & 11 at FIRE_PROTECTION;6 should be deleted, it's not in the lore.
Line 28 at RANCHERS_BOOTS should be added back, it's in the lore.
Aside from that, it looks good.

**Comment by Swedengamer100** [comment]
> Line 10 & 11 at FIRE_PROTECTION;6 should be deleted, it's not in the lore.
> Line 28 at RANCHERS_BOOTS should be added back, it's in the lore.
> Aside from that, it looks good.

Thanks, fixed

**Review by SemicolumnDev — DISMISSED** [review]

**Pull request merged**
